name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - "LICENSE"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      # Ignore files that are not used in production
      - "**.md"
      - "LICENSE"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: checkout
        uses: actions/checkout@v3

      # - name: Install GolangCI-Lint
      #   run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.34.1

      # - name: Run GolangCI-Lint
      #   run: ./bin/golangci-lint run --config .golangci.yml

      - name: test
        run: go test -v ./...
